[tool.poetry]
name = "unipi-data-mining-project"
version = "0.1.0"
description = "Data Mining Project - University of Pisa"
authors = [
    "Abderrahmane Salmi",
    "Ricardo Talarico", 
    "Lorenzo Allegrini"
]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26"
scipy = "^1.11"
pandas = "^2.3.3"
matplotlib = "^3.10.7"
seaborn = "^0.13.2"
nltk = "^3.9.2"
scikit-learn = "^1.7.2"
umap-learn = "^0.5.9.post2"
geopandas = "^1.1.1"
contextily = "^1.7.0"
jupyter = "^1.1.1"
ipykernel = "^7.1.0"
notebook = "^7.5.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
